<?php

// autoload_wordpress.php generated by schlessera/composer-wp-autoload

require_once dirname(__FILE__) . '/composer'.'/autoload_real_wordpress.php';

return ComposerAutoloaderInit0e82b3dc330ca67abc15d988433a9d9b::getLoader();
