<?php

// autoload_wordpress.php generated by schlessera/composer-wp-autoload

require_once dirname(__FILE__) . '/composer'.'/autoload_real_wordpress.php';

return ComposerAutoloaderInitWPd02c56a2fedd820876e05ce9580b834e::getLoader();
