<?php

// autoload_wordpress.php generated by schlessera/composer-wp-autoload

require_once dirname(__FILE__) . '/composer'.'/autoload_real_wordpress.php';

return ComposerAutoloaderInit41b261efe5df97e38483afa3b36719cd::getLoader();
