<?php

// autoload_real_wordpress.php generated by schlessera/composer-wp-autoload

class ComposerAutoloaderInit41b261efe5df97e38483afa3b36719cd {
	private static $loader;

	public static function loadClassLoader($class) {
		if ('WordPress_Composer_ClassLoader' === $class) {
			require dirname(__FILE__).'/ClassLoaderWordPress.php';
		}
	}

	/**
	 * @return WordPress_Composer_ClassLoader
	 */
	public static function getLoader() {
		if (null !== self::$loader) {
			return self::$loader;
		}

		spl_autoload_register(array('ComposerAutoloaderInit41b261efe5df97e38483afa3b36719cd', 'loadClassLoader'), true /*, true */);
		self::$loader = $loader = new WordPress_Composer_ClassLoader();
		spl_autoload_unregister(array('ComposerAutoloaderInit41b261efe5df97e38483afa3b36719cd', 'loadClassLoader'));

		$vendorDir = dirname(dirname(__FILE__));
		$baseDir   = ABSPATH;
		$dir       = dirname(__FILE__);

		$includePaths = require $dir.'/include_paths.php';
		array_push($includePaths, get_include_path());
		set_include_path(implode(PATH_SEPARATOR, $includePaths));

		$map = require $dir.'/autoload_namespaces.php';
		foreach ($map as $namespace => $path) {
			$loader->add($namespace, $path);
		}

		$classMap = require $dir.'/autoload_classmap_wordpress.php';
		if ($classMap) {
			$loader->addClassMap($classMap);
		}

		$loader->register(true);

		require $vendorDir . '/paragonie/random_compat/lib/random.php';

		return $loader;
	}
}
