<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'WordPress\\ComposerAutoload\\' => array($vendorDir . '/schlessera/composer-wp-autoload/src'),
    'POMO\\' => array($vendorDir . '/pomo/pomo/src'),
);
